controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    meca_controller:
      type: joint_trajectory_controller/JointTrajectoryController

meca_controller:
  ros__parameters:
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
      - meca_axis_6_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
